### ISSUE TITLE
segfault panic on running `controller-gen webhook`

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-tools#154]
When run from the root of controller-runtime.  Probably should just be a normal error.

### Reproducer: 

Have CR and CT checked out

```shell
$ cd $GOPATH/src/sigs.k8s.io/controller-runtime
$ go run ../controller-tools/cmd/controller-gen webhook
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x115fbb2]

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/webhook.(*ManifestOptions).labelPatch(0xc0004ec9c0, 0x0, 0x0)
        $GOPATH/src/sigs.k8s.io/controller-tools/pkg/webhook/manifests.go:123 +0x42
sigs.k8s.io/controller-tools/pkg/webhook.Generate(0xc0004ec9c0, 0xc000510500, 0xc000139d30)
        $GOPATH/src/sigs.k8s.io/controller-tools/pkg/webhook/manifests.go:102 +0x671
main.newWebhookCmd.func1(0xc00013d180, 0x21f1870, 0x0, 0x0)
        $GOPATH/src/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go:181 +0x36
sigs.k8s.io/controller-tools/vendor/github.com/spf13/cobra.(*Command).execute(0xc00013d180, 0x21f1870, 0x0, 0x0, 0xc00013d180, 0x21f1870)
        $GOPATH/src/sigs.k8s.io/controller-tools/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
sigs.k8s.io/controller-tools/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000eef00, 0xc000139f68, 0x4, 0x4)
        $GOPATH/src/sigs.k8s.io/controller-tools/vendor/github.com/spf13/cobra/command.go:852 +0x2c0
sigs.k8s.io/controller-tools/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        $GOPATH/src/sigs.k8s.io/controller-tools/vendor/github.com/spf13/cobra/command.go:800
main.main()
       $GOPATH/src/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go:53 +0x166
```

**Comment by DirectXMan12** [comment]
cc @mengqiy 
/kind bug
