### ISSUE TITLE
controller-gen crashed with "fatal error: concurrent map writes"

### ISSUE THREAD

**Issue by wallrj** [kubernetes-sigs/controller-tools#249]
https://travis-ci.com/sky-uk/cassandra-operator/jobs/215146641#L995

```
== validate-types
/home/travis/gopath/src/github.com/sky-uk/cassandra-operator/cassandra-operator/hack/verify-codegen.sh
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 76 [running]:
runtime.throw(0xb8f309, 0x15)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc0000e5ef8 sp=0xc0000e5ec8 pc=0x42d792
runtime.mapassign_fast64ptr(0xac4f40, 0xc000469020, 0xc000ab6a40, 0xc00003f4b0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/map_fast64.go:266 +0x34e fp=0xc0000e5f38 sp=0xc0000e5ef8 pc=0x412e4e
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00003f4b0, 0xc000ab6a40)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:247 +0x195 fp=0xc0000e5fa0 sp=0xc0000e5f38 pc=0x9777e5
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0xc000aa61a0, 0xc00003f4b0, 0xc000ab6a40)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:239 +0x5b fp=0xc0000e5fc8 sp=0xc0000e5fa0 pc=0x97839b
runtime.goexit()
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000e5fd0 sp=0xc0000e5fc8 pc=0x459401
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:237 +0x13f

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00042aaa8)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc00042aaa0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/sync/waitgroup.go:130 +0x65
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00003f4b0, 0xc0001372c0)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:242 +0x160
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).Check(0xc000174a20, 0xc0001372c0, 0xbbdc70)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:205 +0x90
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0xc0000a2dbb, 0x1c, 0x0, 0x0, 0xc00014c460, 0xc6e56c, 0xc000043d60)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/deepcopy/gen.go:140 +0x1ca
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc0000d6780, 0x1)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/genall/genall.go:156 +0x170
main.runGenerators(0xc00017f290, 0x3, 0x3, 0xc0000e9d00, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/cmd/controller-gen/main.go:345 +0x27c
main.main.func1(0xc00017c000, 0xc00017f290, 0x3, 0x3, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/cmd/controller-gen/main.go:217 +0x4a
github.com/spf13/cobra.(*Command).execute(0xc00017c000, 0xc0000aa050, 0x3, 0x3, 0xc00017c000, 0xc0000aa050)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc00017c000, 0xbb4eeb, 0x397, 0xb89c23)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/cmd/controller-gen/main.go:223 +0x238

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x115fba0)
	/home/travis/gopath/pkg/mod/k8s.io/klog@v0.3.0/klog.go:975 +0x8b
created by k8s.io/klog.init.0
	/home/travis/gopath/pkg/mod/k8s.io/klog@v0.3.0/klog.go:404 +0x6c

goroutine 9 [semacquire]:
sync.runtime_Semacquire(0xc000aa61a8)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000aa61a0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/sync/waitgroup.go:130 +0x65
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00003f4b0, 0xc00034be80)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:242 +0x160
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0xc00042aaa0, 0xc00003f4b0, 0xc00034be80)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:239 +0x5b
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:237 +0x13f

goroutine 10 [semacquire]:
sync.runtime_Semacquire(0xc000343068)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000343060)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/sync/waitgroup.go:130 +0x65
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00003f4b0, 0xc00034be60)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:242 +0x160
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0xc00042aaa0, 0xc00003f4b0, 0xc00034be60)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:239 +0x5b
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:237 +0x13f

goroutine 54 [running]:
	goroutine running on other thread; stack unavailable
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:237 +0x13f

goroutine 51 [semacquire]:
sync.runtime_Semacquire(0xc000363404)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000363404)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/sync/waitgroup.go:130 +0x65
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00003f4b0, 0xc0001f9200)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:242 +0x160
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0xc000343060, 0xc00003f4b0, 0xc0001f9200)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:239 +0x5b
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:237 +0x13f

goroutine 54 [running]:
runtime.throw(0xb8f309, 0x15)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/panic.go:617 +0x72 fp=0xc000825ef8 sp=0xc000825ec8 pc=0x42d792
runtime.mapassign_fast64ptr(0xac4f40, 0xc000469020, 0xc0001f90e0, 0xc00003f4b0)
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/map_fast64.go:266 +0x34e fp=0xc000825f38 sp=0xc000825ef8 pc=0x412e4e
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00003f4b0, 0xc0001f90e0)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:247 +0x195 fp=0xc000825fa0 sp=0xc000825f38 pc=0x9777e5
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0xc000363404, 0xc00003f4b0, 0xc0001f90e0)
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:239 +0x5b fp=0xc000825fc8 sp=0xc000825fa0 pc=0x97839b
runtime.goexit()
	/home/travis/.gimme/versions/go1.12.linux.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000825fd0 sp=0xc000825fc8 pc=0x459401
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check
	/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-tools@v0.2.0-beta.2/pkg/loader/refs.go:237 +0x13f
make[1]: *** [validate-types] Error 2
make[1]: Leaving directory `/home/travis/gopath/src/github.com/sky-uk/cassandra-operator/cassandra-operator'
make: *** [install-all] Error 2
travis_time:end:0832c7df:start=1562848005091876221,finish=1562848169195434491,duration=164103558270
[0K[31;1mThe command "make setup install" failed and exited with 2 during .[0m
```

```
go version go1.12 linux/amd64
```

**Comment by jgustie** [comment]
Looks like a dup of #238, should be fixed in beta.3

**Comment by wallrj** [comment]
@jgustie Thanks. We'll update to the latest version and re-open this if we come across the problem again.
