### ISSUE TITLE
controller-gen panics if there is an empty or incomplete go file in your project.

### ISSUE THREAD

**Issue by erictune** [kubernetes-sigs/controller-tools#336]
If you accidentally write an empty or incomplete .go file in your KubeBuilder project and then run `make`, it will invoke controller-gen, which will panic.  I would expect controller-gen to print an error message instead.

Repro:
```
$ cd $GOPATH
$ mkdir src/kb-panic
$ cd src/kb-panic
$ touch oops.go  # can be empty or have invalid go code in it.
$ make
$ make
/Users/etune/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x158551f]

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc000280000, 0xc00011f748)
	/Users/etune/homebrew/Cellar/go/1.13/libexec/src/go/types/check.go:240 +0x98
panic(0x172ac80, 0x1d939f0)
	/Users/etune/homebrew/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2
sync.(*Mutex).Lock(...)
	/Users/etune/homebrew/Cellar/go/1.13/libexec/src/sync/mutex.go:74
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck.func1(0xc00026202b, 0x4, 0x0, 0x0, 0x0)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/loader.go:255 +0xaf
sigs.k8s.io/controller-tools/pkg/loader.importerFunc.Import(0xc000264480, 0xc00026202b, 0x4, 0x0, 0x0, 0x17f8500)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/loader.go:361 +0x3a
go/types.(*Checker).importPackage(0xc000280000, 0x22d, 0xc00026202b, 0x4, 0xc00024c060, 0x20, 0x10)
	/Users/etune/homebrew/Cellar/go/1.13/libexec/src/go/types/resolver.go:161 +0x612
go/types.(*Checker).collectObjects(0xc000280000)
	/Users/etune/homebrew/Cellar/go/1.13/libexec/src/go/types/resolver.go:256 +0x15d9
go/types.(*Checker).checkFiles(0xc000280000, 0xc0002440a8, 0x1, 0x1, 0x0, 0x0)
	/Users/etune/homebrew/Cellar/go/1.13/libexec/src/go/types/check.go:252 +0xad
go/types.(*Checker).Files(...)
	/Users/etune/homebrew/Cellar/go/1.13/libexec/src/go/types/check.go:245
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0001a3b90, 0xc000222240)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/loader.go:284 +0x3b5
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc000222240)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/loader.go:96 +0x5b
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc00027c7a0, 0xc000222240)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/refs.go:249 +0x1f8
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).Check(0xc000222280, 0xc000222240, 0x1827508)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/refs.go:206 +0x90
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage(0xc00011fb10, 0xc000222240, 0x17eb535, 0x5, 0x17ea858)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/deepcopy/gen.go:199 +0x9a
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0xc00002ae1b, 0x19, 0x0, 0x0, 0xc000254050, 0x1d9b100, 0xc000236240)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/deepcopy/gen.go:147 +0x1a5
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc000252000, 0xc00000fac0)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/genall/genall.go:167 +0x16f
main.main.func1(0xc000149400, 0xc00000fac0, 0x2, 0x2, 0x0, 0x0)
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/cmd/controller-gen/main.go:168 +0x99
github.com/spf13/cobra.(*Command).execute(0xc000149400, 0xc00009c190, 0x2, 0x2, 0xc000149400, 0xc00009c190)
	/Users/etune/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000149400, 0xc00000fa60, 0x4, 0x0)
	/Users/etune/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/etune/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/Users/etune/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/cmd/controller-gen/main.go:191 +0x2f5
make: *** [generate] Error 2
```

**Comment by keenJR** [comment]
I agree. I have the same problem.

**Comment by knabben** [comment]
Fixed with https://github.com/kubernetes-sigs/controller-tools/pull/351

```
-: oops.go:1:1: expected 'package', found 'EOF'
/.operator/main.go:19:2: no such package located
Error: not all generators ran successfully
```
