### ISSUE TITLE
controller-gen just panic upon cyclic import

### ISSUE THREAD

**Issue by rockmenjack** [kubernetes-sigs/controller-tools#364]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9a66af]

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc00076f2c0, 0xc0040dd738)
        /usr/lib/go/src/go/types/check.go:240 +0x98
panic(0xb5d340, 0x11f9900)
        /usr/lib/go/src/runtime/panic.go:679 +0x1b2
sync.(*Mutex).Lock(...)
        /usr/lib/go/src/sync/mutex.go:74
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck.func1(0xc006150701, 0x34, 0x0, 0x0, 0x0)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/loader/loader.go:255 +0xaf
sigs.k8s.io/controller-tools/pkg/loader.importerFunc.Import(0xc0061ce4b0, 0xc006150701, 0x34, 0x0, 0x0, 0xc2fa00)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/loader/loader.go:361 +0x3a
go/types.(*Checker).importPackage(0xc00076f2c0, 0x5aebf3, 0xc006150701, 0x34, 0xc0007fb4a0, 0x39, 0x4)
        /usr/lib/go/src/go/types/resolver.go:161 +0x612
go/types.(*Checker).collectObjects(0xc00076f2c0)
        /usr/lib/go/src/go/types/resolver.go:256 +0x15d9
go/types.(*Checker).checkFiles(0xc00076f2c0, 0xc0061609f8, 0x1, 0x1, 0x0, 0x0)
        /usr/lib/go/src/go/types/check.go:252 +0xad
go/types.(*Checker).Files(...)
        /usr/lib/go/src/go/types/check.go:245
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc000190840, 0xc0007224a0)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/loader/loader.go:284 +0x3b5
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc0007224a0)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/loader/loader.go:96 +0x5b
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc0061d40e0, 0xc0007224a0)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/loader/refs.go:249 +0x1f8
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).Check(0xc000722500, 0xc0007224a0, 0xc62678)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/loader/refs.go:206 +0x90
sigs.k8s.io/controller-tools/pkg/deepcopy.(*ObjectGenCtx).GenerateForPackage(0xc0040ddb00, 0xc0007224a0, 0x0, 0x0, 0x0)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/deepcopy/gen.go:199 +0x9a
sigs.k8s.io/controller-tools/pkg/deepcopy.Generator.Generate(0xc0000a8dbb, 0x19, 0x0, 0x0, 0xc0000ca0a0, 0x12011c0, 0xc000192480)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/deepcopy/gen.go:147 +0x1a5
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc0007cae80, 0xc0000a1b20)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/pkg/genall/genall.go:167 +0x16f
main.main.func1(0xc000125680, 0xc0000a1b20, 0x2, 0x2, 0x0, 0x0)
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/cmd/controller-gen/main.go:176 +0xa6
github.com/spf13/cobra.(*Command).execute(0xc000125680, 0xc000094160, 0x2, 0x2, 0xc000125680, 0xc000094160)
        /home/rockmen1/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000125680, 0xc0000a1ac0, 0x4, 0x0)
        /home/rockmen1/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/rockmen1/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/rockmen1/go/pkg/mod/sigs.k8s.io/controller-tools@v0.2.2/cmd/controller-gen/main.go:200 +0x37e
make: *** [Makefile:51: generate] Error 2
```

It took me a whole morning to figure out why...

The root cause was:
package ```controllers``` import some other package which in turns imports ```controllers```

**Comment by hypnoglow** [comment]
Probably fixed in https://github.com/kubernetes-sigs/controller-tools/pull/351
