### ISSUE TITLE
SIGBUS: bus error

### ISSUE THREAD

**Issue by josvazg** [kubernetes-sigs/controller-tools#690]
I can't even run `./test.sh` on a freshly checked out repo:

~~~shell
$ git clone git@github.com:kubernetes-sigs/controller-tools.git
$ cd controller-tools/
$ ./test.sh 
using tools
fetching tools
kubebuilder/
...
kubebuilder/bin/etcd
setting up env vars
generating marker help
# command-line-arguments
unexpected fault address 0x7febb2c3b043
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7febb2c3b043 pc=0x4f986e]

goroutine 1 [running]:
runtime.throw({0x673634?, 0x412439?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00011e638 sp=0xc00011e608 pc=0x4347f1
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:815 +0x125 fp=0xc00011e688 sp=0xc00011e638 pc=0x44a8c5
encoding/binary.littleEndian.Uint64(...)
        /usr/local/go/src/encoding/binary/binary.go:79
cmd/internal/goobj.(*Reader).uint64At(...)
        /usr/local/go/src/cmd/internal/goobj/objfile.go:618
cmd/internal/goobj.(*Reader).Hash64(...)
        /usr/local/go/src/cmd/internal/goobj/objfile.go:763
cmd/link/internal/loader.(*loadState).addSym.func2()
        /usr/local/go/src/cmd/link/internal/loader/loader.go:413 +0x4e fp=0xc00011e6b0 sp=0xc00011e688 pc=0x4f986e
~~~

OS:
~~~shell
$ uname -a
Linux josvaz-p5540 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
~~~

How can I avoid this issue?

**Comment by josvazg** [comment]
Issue persists after a reboot, seems it does not depend on the state of the system.

**Comment by josvazg** [comment]
~~~shell
$ go version
go version go1.18.3 linux/amd64
~~~

**Comment by josvazg** [comment]
Is there any known incompatibility with Go 1.18?

**Comment by josvazg** [comment]
Seems `1.18.2` does not sigbus, bue fails to compile with errors, so I guess this project is not 1.18 ready and 1.18.3 has some bug. I might need to report that one upstream in the go project.

I will need to ensure to use go1.17 for now when using this project.
